

from config import *


def bright_side():
    with open(namefile, 'r') as f:
            name = f.read()
    print("Cheer up, ", name, "", sep='')
    time.sleep(1)
    print("You know what they say...")
    time.sleep(2)
    print()
    print("Some things in life are bad ")
    time.sleep(3)
    print("They can really make you mad ")
    time.sleep(2)
    print("Other things just make you swear and curse ")
    time.sleep(4)
    print("When you're chewing on life's gristle")
    time.sleep(4)
    print("Don't grumble, give a whistle ")
    time.sleep(3)
    print("And this'll help things turn out for the best")
    time.sleep(4)
    print()
    print("And...")
    time.sleep(3)
    print("always look on the bright side of life")
    time.sleep(5)
    print("Always look on the light side of life")
    time.sleep(5)
    print()
    print("If life seems jolly rotten ")
    time.sleep(3)
    print("There's something you've forgotten ")
    time.sleep(3)
    print("And that's to laugh and smile and dance and sing ")
    time.sleep(5)
    print("When you're feeling in the dumps ")
    time.sleep(4)
    print("Don't be silly chumps ")
    time.sleep(3)
    print("Just purse your lips and whistle, that's the thing")
    time.sleep(6)
    print()
    print("And always look on the bright side of life")
    time.sleep(6)
    print("Come on!")
    time.sleep(1)
    print("Always look on the right side of life")
    time.sleep(5)
    print()
    print("For life is quite absurd ")
    time.sleep(4)
    print("And death's the final word ")
    time.sleep(5)
    print("You must always face the curtain with a bow ")
    time.sleep(6)
    print("Forget about your sin")
    time.sleep(4)
    print("Give the audience a grin ")
    time.sleep(4)
    print("Enjoy it, it's your last chance anyhow")
    time.sleep(5)
    print()
    print("So, always look on the bright side of death")
    time.sleep(6)
    print("A-just before you draw your terminal breath")
    time.sleep(6)
    print()
    print("Life's a piece of shit")
    time.sleep(4)
    print("When you look at it")
    time.sleep(4)
    print("Life's a laugh and death's a joke, it's true")
    time.sleep(5)
    print("You'll see it's all a show")
    time.sleep(4)
    print("Keep 'em laughing as you go")
    time.sleep(4)
    print("Just remember that the last laugh is on you")
    time.sleep(6)
    print()
    print("And always look on the bright side of life")
    time.sleep(6)
    print("Always look on the right side of life")
    time.sleep(6)
    print()
    print("C'mon ", name, ", cheer up!", sep='')
    time.sleep(2)
    print()
    print("Always look on the bright side of life")
    time.sleep(6)
    print("Always look on the bright side of life")
    time.sleep(6)
    print()
    print("Worse things happen at sea, you know")
    time.sleep(2)
    print("Always look on the bright side of life")
    time.sleep(7)
    print()
    print("I mean, what have you got to lose")
    time.sleep(2)
    print("You know, you come from nothing, you're going back to nothing")
    time.sleep(4)
    print("What have you lost? Nothing!")
    time.sleep(2)
    print()
    print("Always look on the right side of life....")
    time.sleep(7)
    print()
    print("Nothing will come from nothing, you know what they say?")
    time.sleep(2)
    print("Cheer up you old bugger, c'mon give us a grin!")
    time.sleep(2)
    print("There you are, see, it's the end of the film")
    time.sleep(2)
    print("Incidentally, this record is available in the foyer")
    time.sleep(2)
    print("Some of us have to got live as well, you know")
    time.sleep(2)
    print("Who do you think pays for all this rubbish")
    time.sleep(2)
    print("They're not gonna make their money back, you know")
    time.sleep(2)
    print("I told them, I said to them, Bernie, I said they'll never make their money back...")
    time.sleep(3)


def daisy_daisy():
    print("Daisy, Daisy,")
    time.sleep(2)
    print("Give me your answer do.")
    time.sleep(3)
    print("I'm half crazy")
    time.sleep(2)
    print("All for the love of you")
    time.sleep(4)
    print("It won't be a stylish marriage,")
    time.sleep(4)
    print("I can't afford a carriage")
    time.sleep(4)
    print("But you'll look sweet,")
    time.sleep(3)
    print("Upon the seat,")
    time.sleep(3)
    print("Of my bicycle built for two.")
    time.sleep(5)
